# Log about all supported codecs, current ffmpeg version
log: true
# Support of youtube links
youtube-audio:
  sleep-delay: 20
  bitrate: -1
  volume: 100 # Volume has some "limit", you cannot set very high volume because of audio corruption
  distance: 100 # Default sound distance that will be used
# Support of:
ffmpeg:
  sleep-delay: 20
  bitrate: -1
  volume: 100
  distance: 100